### ISSUE TITLE
Can you upload the trained model?

### ISSUE THREAD

**Issue by vivekpd15** [LaurentBerder/container_detection#2]
Hey,

I loved your project. Is there a trained model that you could share with me? Thanks.

**Comment by LaurentBerder** [comment]
Thanks @vivekpd15 . Unfortunately, file size limit restricts me from sharing a model here.

**Comment by vivekpd15** [comment]
Is it possible for you to share it with me using https://wetransfer.com or GDrive/Dropbox. Would be of great help. Thanks in advance.

**Comment by LaurentBerder** [comment]
Here you go @vivekpd15 . You can get three versions of trained models [here](https://we.tl/t-CAP9rx2JyQ)

**Comment by vivekpd15** [comment]
Thanks @LaurentBerder 

Much appreciated.

**Comment by leetwito** [comment]
Hey @LaurentBerder 
I would very appreciate if you can upload the trained model again, as the link is already expired.
Thanks !
@vivekpd15 or also if you could share it 
:)

**Comment by roulbac** [comment]
@LaurentBerder @vivekpd15 Transfer link has expired unfortunately. Can someone please reupload?

**Comment by LaurentBerder** [comment]
@Roulbac , @leetwito here's [another link](https://we.tl/t-JO5uvFvzTx).

**Comment by roulbac** [comment]
Thanks @LaurentBerder !

**Comment by himansingh** [comment]
@LaurentBerder @Roulbac @leetwito 
Could you guys please share the trained model again ? 
It'd be very much appreciated !

**Comment by LaurentBerder** [comment]
Guys, in this project, you have the keys to labeling your images and training your own model. 
The model I trained was run on a laptop for a few days only (it was only a demo project, not a production one), which gave it rather limited results.

Github doesn't allow docs as large as the model, and I don't intend on reposting them on wetransfer every months.

Any chance you could consider training the model on your server/computer? It probably would yield better results.

**Comment by himansingh** [comment]
@LaurentBerder, I understand your point here. You've probably shared it too many times already.

Can I suggest you [git-lfs](https://github.com/git-lfs/git-lfs/wiki/Installation) for uploading the model ? 
It has support for large files, as large as a couple GB in size - with Git. This should solve git's large file limit issue.

Thanks.

**Comment by masoudpz** [comment]
Thanks @LaurentBerder , Could you please share the weights with me?

**Comment by LaurentBerder** [comment]
@masoudpz @himansingh 
There we go, I uploaded the model and training dataset.
Do bear in mind that the model itself was poorly trained (for lack of budget and manhour), it would probably benefit from being retrained on an extended dataset.

**Comment by masoudpz** [comment]
> @masoudpz @himansingh There we go, I uploaded the model and training dataset. Do bear in mind that the model itself was poorly trained (for lack of budget and manhour), it would probably benefit from being retrained on an extended dataset.

Many Thanks Laurent.
