### ISSUE TITLE
Container ID Detection and Recognition

### ISSUE THREAD

**Issue by AndreKelm** [LaurentBerder/container_detection#5]
Hallo Laurent,

first of all, thanks a lot for sharing your work. I find it very useful! I am working on a follow-up task and would like to use your dataset for it. The need is to read the IDs of containers, but very often they are not readable due to small image reolution in your dataset. Do you have any idea where I can get the image with the original resolution? That would be great, because then I could use your dataset for this, too.

Best regards,
![NotreadableID0012](https://github.com/LaurentBerder/container_detection/assets/60356944/d7926bcd-b4f5-4e5d-8d70-70dc9f6e6a49)

André

**Comment by LaurentBerder** [comment]
Hallo André,

Funny you should be working on this specific follow-up task, as it was one of the possible evolutions I had thought of at the time. But for the first step of the project, which was just to detect containers, I only needed small images (much faster learning).

I got the images from a webscraping program I made (but didn't keep afterwards), from Google Images. So I don't have any other files, unhappily for you.

But I'm sure you could do something similar, and scrape better quality images that would include the container numbers. And then, the fun of manually labeling them will begin... 😉

Cheers,
Laurent
